// Skills
export const DataTechs = [
  {
    id: 1,
    img: "./src/assets/css-3-svgrepo-com.svg",
    name: "CSS",
    star: "★★★★",
  },
  {
    id: 2,
    img: "./src/assets/html-5-svgrepo-com.svg",
    name: "HTML",
    star: "★★★★",
  },
  {
    id: 3,
    img: "./src/assets/javascript-svgrepo-com.svg",
    name: "JavaScript",
    star: "★★★★",
  },
  {
    id: 4,
    img: "./src/assets/node-svgrepo-com.svg",
    name: "Node",
    star: "★★★★",
  },
  {
    id: 5,
    img: "./src/assets/react-svgrepo-com.svg",
    name: "React",
    star: "★★★★",
  },
  {
    id: 6,
    img: "./src/assets/vscode-svgrepo-com.svg",
    name: "VSCode",
    star: "★★★★",
  },
  {
    id: 7,
    img: "./src/assets/mysql-logo-svgrepo-com.svg",
    name: "MYSQL",
    star: "★★★★",
  },
  {
    id: 8,
    img: "./src/assets/netlify-svgrepo-com.svg",
    name: "Netlify",
    star: "★★★★",
  },
  {
    id: 9,
    img: "./src/assets/npm-svgrepo-com.svg",
    name: "NPM",
    star: "★★★★",
  },
  {
    id: 10,
    img: "./src/assets/vite-svgrepo-com.svg",
    name: "Vite",
    star: "★★★★",
  },
  {
    id: 11,
    img: "./src/assets/bootstrap-svgrepo-com.svg",
    name: "Bootstrap",
    star: "★★★",
  },
  {
    id: 12,
    img: "./src/assets/wordpress-svgrepo-com.svg",
    name: "Wordpress",
    star: "★★★",
  },
  {
    id: 13,
    img: "./src/assets/github-svgrepo-com.svg",
    name: "GitHub",
    star: "★★★",
  },
  {
    id: 14,
    img: "./src/assets/angular-svgrepo-com.svg",
    name: "Angular",
    star: "★★",
  },
  {
    id: 15,
    img: "./src/assets/light-solidity-svgrepo-com.svg",
    name: "Solidity",
    star: "★★",
  },
  {
    id: 16,
    img: "./src/assets/php-svgrepo-com.svg",
    name: "PHP",
    star: "★★",
  },
  {
    id: 17,
    img: "./src/assets/sass-svgrepo-com.svg",
    name: "SASS",
    star: "★★",
  },
  {
    id: 18,
    img: "./src/assets/firebase-svgrepo-com.svg",
    name: "Firebase",
    star: "★★",
  },
  {
    id: 19,
    img: "./src/assets/webpack-svgrepo-com.svg",
    name: "Webpack",
    star: "★★",
  },
  {
    id: 20,
    img: "./src/assets/jquery-svgrepo-com.svg",
    name: "Jquery",
    star: "★★",
  },
  {
    id: 21,
    img: "./src/assets/sql-database-sql-azure-svgrepo-com.svg",
    name: "SQL",
    star: "★★",
  },
  {
    id: 22,
    img: "./src/assets/typescript-official-svgrepo-com.svg",
    name: "TypeScript",
    star: "★",
  },
  {
    id: 23,
    img: "./src/assets/python-svgrepo-com.svg",
    name: "Python",
    star: "★",
  },
];
