export const DataSertications = [
  {
    id: 1,
    name: "Universidad JavaScript",
    img: "./src/assets/img/Serticated/UniversidaJavaScript.png",
    description:
      "De cero a experto. JavaScript. Dónde trabajamos con varios fremaworks, usamos las teconogias como JavaScript, HTML, CSS, NODEJS, TypeScript, Angular, FireBase, Angular CLI, Angulas.js.",
    start: "4-5-2023",
    end: "8-5-2023",
    tech: {
      img1: "./src/assets/img/skills/html-5-svgrepo-com.svg",
      img2: "./src/assets/img/skills/css-3-svgrepo-com.svg",
      img3: "./src/assets/img/skills/javascript-svgrepo-com.svg",
      img4: "./src/assets/img/skills/angular-svgrepo-com.svg",
      img5: "./src/assets/img/skills/node-svgrepo-com.svg",
      img6: "./src/assets/img/skills/firebase-svgrepo-com.svg",
      img7: "./src/assets/img/skills/typescript-official-svgrepo-com.svg",
    },
  },
  {
    id: 2,
    name: "Máster Completo De Blockchain y web3",
    img: "./src/assets/img/Serticated/Blockhain.png",
    description:
      "De cero a experto. Bolckchain y Web3. Dónde trabajamos con varios fremaworks, usamos las teconogias como JavaScript, HTML, CSS, NODEJS, React, Solidity, Ganache, Docker, Truffle Suite, Hardhat, Python, Web3.js, Remix IDE, IPFS, Ether.js, Docker.",
    start: "20-6-2023",
    end: "2-7-2023",
    tech: {
      img1: "./src/assets/img/skills/html-5-svgrepo-com.svg",
      img2: "./src/assets/img/skills/css-3-svgrepo-com.svg",
      img3: "./src/assets/img/skills/javascript-svgrepo-com.svg",
      img4: "./src/assets/img/skills/react-svgrepo-com.svg",
      img5: "./src/assets/img/skills/node-svgrepo-com.svg",
      img6: "./src/assets/img/skills/light-solidity-svgrepo-com.svg",
      img7: "./src/assets/img/skills/python-svgrepo-com.svg",
    },
  },
  {
    id: 3,
    name: "Dessarollo De Mini Aplicación Web",
    img: "./src/assets/img/Serticated/HackABoss1.png",
    description:
      "Desarrollo web Full-Stack. JavaScript. Dónde trabajamos con varios fremaworks, usamos las teconogias como JavaScript, HTML, CSS, MySql NODEJS, React, Vite, Workbench, Postman, Git Bash, GitLap, GitHub, NPM, Express.",
    start: "2-11-2023",
    end: "14-3-2024",
    tech: {
      img1: "./src/assets/img/skills/html-5-svgrepo-com.svg",
      img2: "./src/assets/img/skills/css-3-svgrepo-com.svg",
      img3: "./src/assets/img/skills/javascript-svgrepo-com.svg",
      img4: "./src/assets/img/skills/react-svgrepo-com.svg",
      img5: "./src/assets/img/skills/node-svgrepo-com.svg",
      img6: "./src/assets/img/skills/mysql-logo-svgrepo-com.svg",
      img7: "./src/assets/img/skills/github-svgrepo-com.svg",
    },
  },
  {
    id: 4,
    name: "Aprovechamiento y Asistecia",
    img: "./src/assets/img/Serticated/HackABoss2.png",
    description:
      "Desarrollo web Full-Stack. JavaScript. Dónde trabajamos con varios fremaworks, usamos las teconogias como JavaScript, HTML, CSS, MySql NODEJS, React, Vite, Workbench, Postman, Git Bash, GitLap, GitHub, NPM, Express.",
    start: "2-11-2023",
    end: "14-3-2024",
    tech: {
      img1: "./src/assets/img/skills/html-5-svgrepo-com.svg",
      img2: "./src/assets/img/skills/css-3-svgrepo-com.svg",
      img3: "./src/assets/img/skills/javascript-svgrepo-com.svg",
      img4: "./src/assets/img/skills/react-svgrepo-com.svg",
      img5: "./src/assets/img/skills/node-svgrepo-com.svg",
      img6: "./src/assets/img/skills/mysql-logo-svgrepo-com.svg",
      img7: "./src/assets/img/skills/github-svgrepo-com.svg",
    },
  },
  {
    id: 5,
    name: "Aptitud En Pruebas Técnicas",
    img: "./src/assets/img/Serticated/HackABoss3.png",
    description:
      "Desarrollo web Full-Stack. JavaScript. Dónde trabajamos con varios fremaworks, usamos las teconogias como JavaScript, HTML, CSS, MySql NODEJS, React, Vite, Workbench, Postman, Git Bash, GitLap, GitHub, NPM, Express.",
    start: "2-11-2023",
    end: "14-3-2024",
    tech: {
      img1: "./src/assets/img/skills/html-5-svgrepo-com.svg",
      img2: "./src/assets/img/skills/css-3-svgrepo-com.svg",
      img3: "./src/assets/img/skills/javascript-svgrepo-com.svg",
      img4: "./src/assets/img/skills/react-svgrepo-com.svg",
      img5: "./src/assets/img/skills/node-svgrepo-com.svg",
      img6: "./src/assets/img/skills/mysql-logo-svgrepo-com.svg",
      img7: "./src/assets/img/skills/github-svgrepo-com.svg",
    },
  },
  {
    id: 6,
    name: "Crea Una Tienda Online",
    img: "./src/assets/img/Serticated/TiendaOnline.png",
    description:
      "De cero. WordPress. Dónde trabajamos con WordPress, usamos las tecnologías y Plugins como WordPress, Elementor, Paypal, PHP, Yoast SEO, WPForms Lite, WP Mail SMTP, WP Show Posts, Adapta RGPD",
    start: "27-9-2023",
    end: "29-9-2023",
    tech: {
      img1: "./src/assets/img/skills/wordpress-svgrepo-com.svg",
      img2: "./src/assets/img/skills/php-svgrepo-com.svg",
      img3: "./src/assets/img/skills/wordpress-svgrepo-com.svg",
      img4: "./src/assets/img/skills/wordpress-svgrepo-com.svg",
      img5: "./src/assets/img/skills/wordpress-svgrepo-com.svg",
      img6: "./src/assets/img/skills/wordpress-svgrepo-com.svg",
      img7: "./src/assets/img/skills/wordpress-svgrepo-com.svg",
    },
  },
];
