// Skills
export const DataTechs = [
  {
    id: 1,
    img: "../../public/Skills/css-3-svgrepo-com.svg",
    name: "CSS",
    star: "95",
  },
  {
    id: 2,
    img: "../../public/Skills/html-5-svgrepo-com.svg",
    name: "HTML",
    star: "95",
  },
  {
    id: 3,
    img: "../../public/Skills/javascript-svgrepo-com.svg",
    name: "JavaScript",
    star: "95",
  },
  {
    id: 4,
    img: "../../public/Skills/node-svgrepo-com.svg",
    name: "Node",
    star: "95",
  },
  {
    id: 5,
    img: "../../public/Skills/react-svgrepo-com.svg",
    name: "React",
    star: "95",
  },
  {
    id: 6,
    img: "../../public/Skills/vscode-svgrepo-com.svg",
    name: "VSCode",
    star: "95",
  },
  {
    id: 7,
    img: "../../public/Skills/mysql-logo-svgrepo-com.svg",
    name: "MYSQL",
    star: "95",
  },
  {
    id: 8,
    img: "../../public/Skills/netlify-svgrepo-com.svg",
    name: "Netlify",
    star: "80",
  },
  {
    id: 9,
    img: "../../public/Skills/npm-svgrepo-com.svg",
    name: "NPM",
    star: "95",
  },
  {
    id: 10,
    img: "../../public/Skills/vite-svgrepo-com.svg",
    name: "Vite",
    star: "90",
  },
  {
    id: 11,
    img: "../../public/Skills/bootstrap-svgrepo-com.svg",
    name: "Boostrap",
    star: "70",
  },
  {
    id: 12,
    img: "../../public/Skills/wordpress-svgrepo-com.svg",
    name: "Wordpress",
    star: "40",
  },
  {
    id: 13,
    img: "../../public/Skills/github-svgrepo-com.svg",
    name: "GitHub",
    star: "70",
  },
  {
    id: 14,
    img: "../../public/Skills/angular-svgrepo-com.svg",
    name: "Angular",
    star: "20",
  },
  {
    id: 15,
    img: "../../public/Skills/light-solidity-svgrepo-com.svg",
    name: "Solidity",
    star: "20",
  },
  {
    id: 16,
    img: "../../public/Skills/php-svgrepo-com.svg",
    name: "PHP",
    star: "20",
  },
  {
    id: 17,
    img: "../../public/Skills/sass-svgrepo-com.svg",
    name: "SASS",
    star: "20",
  },
  {
    id: 18,
    img: "../../public/Skills/firebase-svgrepo-com.svg",
    name: "Firebase",
    star: "20",
  },
  {
    id: 19,
    img: "../../public/Skills/webpack-svgrepo-com.svg",
    name: "Webpack",
    star: "20",
  },
  {
    id: 20,
    img: "../../public/Skills/jquery-svgrepo-com.svg",
    name: "Jquery",
    star: "20",
  },
  {
    id: 21,
    img: "../../public/Skills/sql-database-sql-azure-svgrepo-com.svg",
    name: "SQL",
    star: "20",
  },
  {
    id: 22,
    img: "../../public/Skills/typescript-official-svgrepo-com.svg",
    name: "TypeScript",
    star: "10",
  },
  {
    id: 23,
    img: "../../public/Skills/python-svgrepo-com.svg",
    name: "Python",
    star: "10",
  },
  {
    id: 24,
    img: "../../public/Skills/react-svgrepo-com.svg",
    name: "React-Native",
    star: "10",
  },
  {
    id: 25,
    img: "../../public/Skills/node-svgrepo-com.svg",
    name: "Expres",
    star: "90",
  },
];
